### ISSUE TITLE
Issue with example code

### ISSUE THREAD

**Issue by cgrace1978** [ollyburren/cupcake#2]
I think I have found an issue with some of the example code in the tutorial, specifically with the data pre-processing step:

https://ollyburren.github.io/cupcake/articles/project-basis.html#data-preprocessing

The line in the tutorial reads:
`## in this case the effect allele is the wrong way around and so we need to flip`
`M[ref_a1==a2 & ref_a2==a1,flip_allele:=TRUE][,c('a1','a2','or'):=list(a2,a1,1/or)][]`

This line applies the flip to all the entries in the data.frame. 

I thnk the code should actually read: 
`M[ref_a1==a2 & ref_a2==a1,c('flip_allele','a1','a2','or'):=list(TRUE, a2,a1,1/or)]`

This applies the flip only to the entries which require it.

Many Thanks,

Chris Grace

**Comment by ollyburren** [comment]
Dear Chris G. Thanks for pointing out this error which should now be fixed. I will rebuild the pkgdown vignette and redeploy. Thanks once again. Olly
